#inherit_from: ./rubocop/rubocop-todo.yml

AllCops:
  Include:
    - 'lib/*'
    - 'lib/**/*'
  Exclude:
    - 'samples/*'

SpaceAroundOperators:
  Enabled: false

SpaceAfterComma:
  Enabled: false

SpaceBeforeBlockBraces:
  EnforcedStyle: no_space

SpaceInsideBlockBraces:
  EnforcedStyle: no_space

SpaceInsideBlockBraces:
  Enabled: false

TrailingWhitespace:
  Enabled: false

SingleLineMethods:
  Enabled: false

AndOr:
  Enabled: false
